hyperledger/firefly-cli

cmd/logs.go, cmd/remove.go, cmd/root.go, cmd/start.go, cmd/stop.go, go.mod, go.sum, internal/docker/docker.go, internal/stacks/stack.go
To enable verbose logs add `-v` anywhere to the command line
To disable fancy features such as colors and spinners, add the `--ansi never` flag to the command line
=> Add verbose flag. Make fancy features optional.

cmd/init.go, cmd/logs.go, cmd/stop.go, internal/stacks/fireflyConfig.go, internal/stacks/stack.go
This PR changes the default config for FireFly core to skip subscription initialization the first time it comes up. It then loads the contracts into ethconnect. It will then shut down each FireFly core node, change its config to not skip subscription initialization, and then start each node again.
This means that when the `start` command returns, the entire stack should be ready to use.
=> Fix startup crash on FireFly core

README.md, cmd/init.go, cmd/remove.go, cmd/reset.go, cmd/stop.go, internal/stacks/dataExchange.go, internal/stacks/dockerConfig.go, internal/stacks/fireflyConfig.go, internal/stacks/fireflyIdentity.go, internal/stacks/stack.go
This PR adds support for https://github.com/hyperledger-labs/firefly-dataexchange-https.
Other notable improvements include:
- More error propagation throughout
- The `reset` and `remove` commands automatically perform `stop` first so you don't have to. This prevents stacks from getting into weird states where their data has been deleted but the containers themselves haven't been.
=> Data exchange integration

cmd/info.go, cmd/init.go, cmd/logs.go, cmd/ls.go, cmd/remove.go, cmd/reset.go, cmd/start.go, cmd/stop.go, cmd/upgrade.go, internal/stacks/dockerConfig.go, internal/stacks/stack.go
This PR adds `ff upgrade` `ff info`, and `ff ls` commands. There are probably more things we want to add to `info` but this is a start. Right now it shows you the versions of the images your stack is using and the status of any running containers. It also shows you the path to the `docker-compose.yml` if you want to go tinker with it. (`ff init` also prints this out when it finishes now too).
`ff upgrade` can be used to grab the latest versions of each image used in the stack. This should not result in data loss in the stack, so it should be useful for testing backwards compatibility of apps built on FireFly. Data loss during upgrade is prevented due to the fact that all data generated by the system has moved to the `~/.firefly/stacks/<stack_name>/data` directory now.
`ff ls` will list …
=> Add upgrade, info, and ls commands

internal/docker/docker.go
On my machine `docker-compose` now fails with:
`Docker Compose is now in the Docker CLI, try 'docker compose up'`
In order to work this out, I found it easiest to implement #27
=> Capture exit code and stdout/stderr if commands fail and print for users

cmd/init.go, internal/stacks/fireflyIdentity.go
If HTTP requests for registration fail, it causes problems setting up the environment. This wraps those HTTP requests in a retry loop (up to 30 seconds) which should prevent errors due to slight timing inconsistencies in processes startup.
=> Retry registration HTTP requests

cmd/init.go, cmd/start.go, internal/stacks/dockerConfig.go, internal/stacks/stack.go
- Exposes ports for all services, to aid running of firefly outside of compose
- Fixes IPFS which was exposing port `5000` rather than `5001`
- Avoids port `6000` which Chrome does not like querying (for when `/webui` is enabled for IPFS)
- Allows commandline options `-p` and `-s` to configure the base ports
- FireFly base port - default 5000 with increment of 1 for each member (5000,5001,5002 etc.)
- Service base port - default 5100 with increment of 100 for each member (5100, 5200, 5300 etc.)
- Allows `docker pull` to be disabled during `ff start`, for developers with locally built images
- `ff start -n mystack`
- Will update the e2e test to use this
=> Suggested improvements for local dev

README.md, internal/stacks/dockerConfig.go, internal/stacks/ganache/healthcheck.sh
This PR adds an extra step to the ganache healthcheck, using `grep` to make sure that we actually get an HTTP upgrade response for the websocket. The previous code just assumed that if it didn't exit immediately that it was successful, which is not always a safe assumption. This also allows us to shorten the timeouts a bit, which should shave a few seconds off the stack startup time.
=> Improve ganache healthcheck and shorten timeouts

internal/stacks/fireflyConfig.go
This fixes the swagger UI not working correctly on Windows, or anywhere where the external HTTP URL differs from the IP address that the HTTP server is listening on.
=> Add public URL to FireFly config

cmd/init.go, internal/stacks/dockerConfig.go, internal/stacks/fireflyConfig.go, internal/stacks/stack.go
This PR adds the ability to select between the different database implementations available in FireFly. This is part of the `init` command. Example
```
ff init my_stack --database=sqlite3
```
Available options are: `[postgresql sqlite3 sqlitego]`
=> Select between database implementations

cmd/init.go
A small bug was recently introduced that sets the database selection to an empty string. This sets the default to `sqlite3` which was the intended behavior in the previous PR.
=> Fix default database selection

internal/stacks/fireflyConfig.go
With SQLite default parameters, the following error is reasonably likely under load:
```
{"error":"FF10116: Database insert failed: database is locked"}
```
Setting a `_busy_timeout` on the SQLite URL by default should reduce the likelihood of this.
Lots more interesting information here: https://github.com/mattn/go-sqlite3/issues/274
=> Set _busy_timeout=5000 by default

internal/contracts/contracts.go, internal/stacks/stack.go
This also revealed that it's not necessary to separately call
RegisterContract if DeployContract was already called on the node with
registeredName (it returns 409 since the contract was already registered).
Signed-off-by: Andrew Richardson <andrew.richardson@kaleido.io>
=> Check HTTP status code for contract deploy

internal/stacks/stack.go
This is no longer used. It will be superceded by the new work on Tokens
when available.
=> Do not deploy Payment contract

cmd/start.go, internal/stacks/fireflyIdentity.go, internal/stacks/stack.go
* Add --no-rollback -b flag to change new rollback default behavior
* Add 60 second timeout on member registration
* Clean up logging on stack startup
closes #70
=> Automatically rollback failed first time setup

cmd/init.go, internal/stacks/stack.go, internal/stacks/types.go
This is a start for support for several different blockchain providers. This just adds the command line interface options to specify which provider you want. `geth` is the only valid option currently. It's also written to the `stack.json` now so future versions of the CLI should be able to read `stack.json` files created with this code and be able to load that stack.
=> Add command line flag for customizing provider

cmd/init.go, internal/docker/docker_config.go, internal/stacks/stack_manager.go
Fixes:
- PostgreSQL always being selected regardless of command line arguments
- SIGSEGV when using an external node
- SIGSEGV when using an external node with postgres
- Startup sequence not listening on correct port for external processes on first time startup
=> Fix bugs with initialization and starting

internal/stacks/stack_manager.go, internal/tokens/erc1155/erc1155_provider.go
This fixes a timing issue on starting a stack after it's been stopped. Also requires https://github.com/hyperledger-labs/firefly-tokens-erc1155/pull/20 to be merged.
=> Add healthcheck for tokens

cmd/init.go, internal/core/firefly_config.go, internal/stacks/firefly_identity.go, internal/stacks/stack_manager.go, pkg/types/stack.go
This supports interactive adding of names only. Could not come up with a clean way
to do non-interactively - may need a general override mechanism for config keys.
Signed-off-by: Andrew Richardson <andrew.richardson@kaleido.io>
=> Add --prompt-names option for overriding org/node names

internal/core/firefly_config.go
These are no longer needed nor supported (as of https://github.com/hyperledger/firefly/pull/329).
Signed-off-by: Andrew Richardson <andrew.richardson@kaleido.io>
=> Remove "skipEventstreamInit" parameters

.gitignore, cmd/init.go, cmd/start.go, internal/constants/constants.go, internal/core/firefly_config.go, internal/docker/docker_config.go, internal/stacks/prometheus_config.go, internal/stacks/stack_manager.go, pkg/types/stack.go
Closes #121
Adds support for optionally enabling the FireFly metrics server and including a Prometheus server container configured to scrape each FireFly's metrics.
For example, one can create a stack w/ Prometheus enabled (custom manifest used for latest FF image):
```bash
./ff/ff init --prometheus-enabled=true --manifest=${HOME}/github.com/kaleido-io/firefly-cli/manifest.json dev
```
results in:
=> Support for Prometheus Metrics Aggregation

internal/tokens/erc1155/erc1155_provider.go
`ETHCONNECT_IDENTITY` was removed in this commit: https://github.com/hyperledger/firefly-tokens-erc1155/commit/ab737c7caef0b88050457e7e0dd528ce45cc1d57
=> Remove deprecated tokens ETHCONNECT_IDENTITY param

internal/core/firefly_config.go
To prevent the change event queue from becoming exhausted, as discovered in [this issue](https://github.com/hyperledger/firefly/issues/376), the buffer size of `dbevents` must be explicitly stated in the firefly node config.
=> [dbevents-buffersize] adding EventConfig for firefly_config generator

internal/docker/docker_config.go
Adding the stack name in front of the prometheus container name. This allows multiple stacks to have prometheus enabled on the same machine
=> [prom_img_name] adding stack name in front of prometheus container name

internal/stacks/stack_manager.go
Previously the CLI was posting a stringified JSON object to the config endpoint, rather than actual JSON, which caused FireFly to overwrite the entire admin section of the config. This meant that after FireFly re-applies the new config, it just reverts to the default config value for all the admin settings. It was trying to set all of `config.admin` to one big long string. This fix sends _actual JSON_ which allows FireFly to properly patch the config, rather than overwriting the entire section (with a nonsense string)
=> Fix payload for config endpoint

cmd/init.go
The `--prometheus-enabled` flag was inadvertently removed from `cmd/init.go` in a previous merge. This is to add it back
Signed-off-by: David Echelberger <david.echelberger@kaleido.io>
=> [add-back-prom] adding back prometheus

internal/blockchain/fabric/fabric_provider.go
arm64 machines such as Apple's m1 series can run linux/amd64 images via Docker Desktop's emulation, but will produce the following warning that causes some command JSON output parsing to fail:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Because Fabric so far only publishes linux/amd64 images, and they seem to work fine running under the emulation on m1 machines, we can simply force the platform to be linux/amd4 during docker run in order to suppress the warning
=> Add --platform linux/amd64 to suppress Docker warnings

internal/blockchain/ethereum/geth/geth_provider.go, internal/constants/constants.go, internal/stacks/ipfs_config.go
This PR contains a couple of fixes to be able to run FireFly on 64 bit ARM based processors, like M1 Macs.
IPFS has been downgraded to 0.10.0 until https://github.com/ipfs/go-ipfs/issues/8645 is fixed
Go Ethereum has been upgraded to 1.10 as it provides native arm64 builds
Resolves https://github.com/hyperledger/firefly-cli/issues/136
=> Fixes for running on arm64

internal/blockchain/fabric/fabric_provider.go
While investigating https://github.com/hyperledger/firefly/issues/537 I discovered that we weren't actually using the version of fabconnect listed in the manifest, and were always pulling latest still. This caused lots of inconsistencies depending on when someone pulled the stack and sometimes resulted in a broken stack.
=> Use fabconnect image version in manifest

cmd/deploy.go, cmd/prompt.go, internal/blockchain/blockchain_provider.go, internal/blockchain/ethereum/besu/besu_provider.go, internal/blockchain/ethereum/contracts.go, internal/blockchain/ethereum/ethconnect/client.go, internal/blockchain/ethereum/geth/geth_provider.go, internal/blockchain/fabric/fabric_provider.go, internal/core/http.go, internal/stacks/firefly_identity.go, internal/stacks/stack_manager.go, internal/tokens/erc1155/contracts.go, internal/tokens/erc1155/erc1155_provider.go, internal/tokens/erc20erc721/erc20_erc721_provider.go
This PR adds a `deploy` command which can be used by test and other automation tools to deploy pre-compiled contracts. The syntax of the command is `ff deploy <stack_name> <file_name>`. If there is more than one contract in the file, a prompt will appear asking which contract to deploy.
Resolves https://github.com/hyperledger/firefly-cli/issues/151
=> Add deploy command

cmd/init.go, go.mod, go.sum, internal/core/firefly_config.go, internal/stacks/stack_manager.go
This PR adds a new flag `--core-config` (there is no shorthand version) to point to a yaml file which will be overlaid on top of the default FireFly core config file for each member. It uses the conflate library (https://github.com/miracl/conflate) to do the YAML merging.
=> Add flag for extra core config

internal/core/firefly_config.go
Signed-off-by: Gabriel Indik <gabriel.indik@kaleido.io>
=> Switch from https to ffdx

cmd/init.go, cmd/start.go, internal/docker/docker_config.go, internal/stacks/stack_manager.go, pkg/types/options.go, pkg/types/stack.go
The CLI now starts up the FireFly sandbox by default. Customize this with the `--sandbox-enabled` flag.
=> CLI includes FF sandbox

internal/blockchain/ethereum/geth/client.go
The geth JSON RPC client code in the FireFly CLI is wrapped in a retry / delay loop, but the function which unlocks an account wasn't returning errors properly. It would return an error if the HTTP request itself failed (for example if the server wasn't listening) or if the HTTP status code was something other than `200`. However, when a JSON RPC server has a problem fulfilling a request, they usually return `200 OK` and put the specific JSON RPC error code / message inside the JSON response body. For example:
```
> POST / HTTP/1.1
> Host: localhost:5100
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 168
>
} [168 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Fri, 15 Apr 2022 …
```
=> Return JSON RPC errors for personal_unlockAccount

internal/stacks/stack_manager.go
The `ff info` command needed to be adjusted after the move to separate `init` / `runtime` directories in `v0.0.47`. This PR fixes that.
=> Fix info command

internal/constants/constants.go, internal/docker/docker_config.go, internal/stacks/stack_manager.go
This PR adds the Sandbox to the list of images that get pulled as a part of the `PullStack` function.
Perhaps more controversially (though I can't recall why), this PR also adds `PullStack` to the `firstTimeSetup` function. @peterbroadhurst @awrichar can you think of any reason why this is not a good idea?
=> Pull stack images before first start, including Sandbox

internal/blockchain/ethereum/geth/genesis.go, internal/stacks/stack_manager.go
Without this fix, we always pull `ethconnect` - even if `"local": true` is set in the manifest
=> Avoid double pulling images that are in service list - breaking `"local: true`

cmd/deploy_ethereum.go, cmd/init.go, cmd/start.go, internal/blockchain/blockchain_provider.go, internal/blockchain/ethereum/besu/besu_provider.go, internal/blockchain/ethereum/contracts.go, internal/blockchain/ethereum/ethconnect/client.go, internal/blockchain/ethereum/geth/geth_provider.go, internal/blockchain/fabric/fabric_provider.go, internal/stacks/stack_manager.go, internal/tokens/erc1155/contracts.go, internal/tokens/erc1155/erc1155_provider.go, internal/tokens/erc20erc721/contracts.go, internal/tokens/erc20erc721/erc20_erc721_provider.go, internal/tokens/tokens_provider.go, internal/tokens/types.go, pkg/types/contracts.go
This PR makes the ERC-20 / ERC-721 token connector the default. It also deploys the newly packaged TokenFactory contract (in FireFly v1.0.0-rc.6) to streamline the process for users being able to experiment with tokens with external wallets like Metamask.
=> Make ERC-20 / ERC-721 default

internal/blockchain/ethereum/ethsigner/ethsigner.go, internal/constants/constants.go, internal/core/firefly_config.go, internal/docker/docker_config.go, internal/stacks/fftm_config.go, internal/stacks/stack_manager.go, pkg/types/stack.go
- Updates FFTM images to work with new alpha
- Updates FireFly Signer image to latest release
- Adds an `spi` config section for the new SPI, which supersedes the Admin API
- Note the old `admin` config section is not removed, as the FireFly CLI needs to generate config that works for the V1.0.x stream still, and without this section the admin API would be turned off in V1.0.x
With this the instructions in https://gist.github.com/peterbroadhurst/63b147c679f76d485523650e76796009 can be executed successfully (instructions updated to use the `alpha` channel, rather than source builds).
=> SPI updates for new alpha

pkg/types/namespace.go
until @awrichar's changes in https://github.com/spf13/viper/pull/1387 are released, `firstEvent` must be lowercase for ff core to parse successfully.
=> lowercase `firstevent` json for ffcore parsing

internal/stacks/stack_manager.go, pkg/types/namespace.go
Since the Viper patch has been absorbed into main, it's OK to use
camelCase in config files again.
Counterpart to https://github.com/hyperledger/firefly/pull/988
=> Restore camelCase key names

internal/docker/docker_checks.go, internal/docker/docker_config.go, internal/stacks/stack_manager.go
This will reduce the number of docker containers needed to run when multiparty mode has been disabled. Previously, IPFS and DX were there just sitting idle.
=> Skip creation of IPFS and DX when multiparty is disabled

CONTRIBUTING.md
replacing `https://hyperledger.github.io/firefly/contributors/contributors.html` with `https://hyperledger.github.io/firefly/contributors/`
=> Fix link to contributor's guide

cmd/logs.go, internal/docker/docker.go
Closes https://github.com/hyperledger/firefly-cli/issues/214
Signed-off-by: Matthew Whitehead <matthew.whitehead@kaleido.io>
=> Print logs to stdout without needing --verbose to be specified

cmd/init.go, cmd/init_ethereum.go, cmd/init_fabric.go, internal/blockchain/fabric/fabric_provider.go, internal/stacks/stack_manager.go, pkg/types/options.go, pkg/types/stack.go
We've had support for external Ethereum RPC nodes for a while now, but we've never had full support for external (not generated by the FireFly CLI) Fabric networks. There's still a fair amount of manual config editing necessary to create a Fabric Common Connection Profile, but I am not aware of any tooling that can autogenerate that at the moment.
There is a corresponding tutorial for using this new capability here:
https://github.com/kaleido-io/firefly/blob/fabric-test-network-tutorial/docs/tutorials/chains/fabric_test_network.md
This PR also splits out the `init` command into two subcommands so we can keep Ethereum and Fabric specific flags separate. The new commands are:
- `ff init ethereum ...`
- `ff init fabric ...`
The existing `ff init` command continues to maintain backwards …
=> Add support for external Fabric networks

.github/workflows/build.yml, .github/workflows/e2e.yml, cmd/init_ethereum.go
This PR fixes the fact that `ff init` and `ff init ethereum` had different default options which was confusing and not working correctly because one would override the other
=> Fix default ethereum connector

internal/blockchain/ethereum/besu/besu_provider.go, internal/blockchain/ethereum/connector/connector_interface.go, internal/blockchain/ethereum/connector/ethconnect/config.go, internal/blockchain/ethereum/connector/evmconnect/config.go, internal/blockchain/ethereum/geth/geth_provider.go, internal/blockchain/ethereum/remoterpc/remoterpc_provider.go, internal/stacks/prometheus_config.go, internal/stacks/stack_manager.go, pkg/types/organization.go
This PR relates to PR https://github.com/hyperledger/firefly-transaction-manager/pull/41 which adds support for prometheus metrics in FFTM.
Signed-off-by: Matthew Whitehead <matthew.whitehead@kaleido.io>
=> When --prometheus-enabled is set, add FFTM metric configuration to prometheus.yml and evmconnect_*.yaml

README.md
Binary move path was incorrect in the heading compared with the path mentioned in the code.
Signed-off-by: Dinkar Jain <62498436+dinkar-jain@users.noreply.github.com>
=> Corrected binary move path in heading

CONTRIBUTING.md, cmd/deploy_ethereum.go
I think when the fabric and ethereum commands were split out the argument checking became too strict and prevent the "params" JSON header from being set to anything other than an empty array. For smart contracts with constructors that take parameters this means you can't provide the vars needed at deploy time.
=> Allow contract constructor params

cmd/accounts_create.go, cmd/accounts_list.go, cmd/deploy_ethereum.go, cmd/deploy_fabric.go, cmd/info.go, cmd/logs.go, cmd/remove.go, cmd/reset.go, cmd/start.go, cmd/stop.go, go.mod, go.sum, internal/docker/docker.go, internal/docker/docker_checks.go
I'm not a golang developer, so any code presented here is a collection of educated guesses as how to solve the problem.
With that out of the way, let's present the pull request.
This pull request adresses [Issue231: firefly fails check for docker compose v2](https://github.com/hyperledger/firefly-cli/issues/231). The problem arises due to docker changing the syntax for docker-compose from `docker-compose` in version 1 to `docker compose` in version 2. There is always the workaround to require the standalone docker-compose in version 1.
The fix is split into two parts, adressing the checking of the version and integrating the information into the stack manager that executes the docker commands via `RunDockerComposeCommand`. The information about which version syntax to use for the commands …
=> first draft for supporting docker-compose v2

cmd/init_ethereum.go, cmd/init_fabric.go, cmd/pull.go, cmd/upgrade.go, internal/core/config.go, internal/docker/docker_config.go, internal/log/spin.go, internal/stacks/stack_manager.go
This is a significant change to the way the upgrade command works. Unfortunately I don't think it has really worked for quite some time, due to the way we pin images to specific shas. This change will rewrite the stack.json file and the docker-compose.yml file with the correct image name/tag/sha for the desired version. In theory this also allows for downgrades as well, though that's untested. I successfully tested upgrading from v1.1.3 -> v1.2.0-rc.3. I also tested the same migration with Besu and that worked as well.
Due to the filesystem location of the sqlite DB in previous versions of the FireFly CLI unfortunately the DB is lost in the upgrade. This PR fixes that and stacks created with this version should be upgradable to future FireFly versions. But unfortunately it means that …
=> Fix upgrade command

internal/docker/docker.go, internal/docker/docker_checks.go, internal/stacks/stack_manager.go, pkg/types/namespace.go
The yaml serializer was missing the `omitempty` tag so even though the Go code wasn't setting a value, the `firstEvent` field was getting written to the config as an empty string `""`. Setting it to an empty string causes FireFly to _not_ apply its default setting, which can result in the blockchain connector subscribing from the newest event, rather than the oldest.
=> Do not set firstEvent to empty string

cmd/init_fabric.go, internal/stacks/stack_manager.go, pkg/types/namespace.go, pkg/types/options.go, pkg/types/stack.go
Part of [FIR-17](https://github.com/hyperledger/firefly-fir/pull/17)
Required by https://github.com/hyperledger/firefly/pull/1213
=> Add Fabric option for a global (channel-wide) batch pin listener

internal/stacks/stack_manager.go
It currently takes me about 5 attempts to start up a dev environment, because the CLI expects me to task-switch back to my commandline within a 2min window (having task switched out to doing something else, when I kicked off `ff start`).
So I'm raising this as a proposal to give me 10mins instead. Hope that's ok
=> Allow longer before giving up on dev starting a firefly core

.github/workflows/build.yml, .goreleaser.yml, internal/blockchain/fabric/fabric_provider.go
the `label` property has the value that is a combination of the chaincode name version. for instance if the chaincode name is `basic`, and version is `v2.0`, then the label is returned as `basic_v2.0`, using the convention `_` to concatenate the two parts:
```
{
"installed_chaincodes": [
{
"package_id": "firefly_1.0:b8e754685421dd03e40251b9ef2dd811e49659453cd489ca7bd27585d9be06b4",
"label": "firefly_1.0",
"references": {
"firefly": {
"chaincodes": [
{
"name": "firefly",
"version": "1.0"
}
]
}
}
},
{
"package_id": "basic_v1.0:351b39eb21c6a1d42f65d21398bf747880404c322a8883f2fb61fe1a3bb0d68d",
"label": "basic_v1.0"
}
]
}
```
=> Fix checking result of queryInstalled()

.github/workflows/build.yml, .goreleaser.yml
Resolves https://github.com/hyperledger/firefly-cli/issues/249
Also updates the goreleaser action to v4
=> Fix Goreleaser Job

.github/workflows/build.yml, .github/workflows/e2e.yml, .github/workflows/release.yml
Apparently Goreleaser is now picky about doing builds against commits that don't match the tag that it's expecting. The version of Goreleaser that we're using was recently upgraded which caused this change. Previously, (I'm not sure why) we were running Goreleaser on every PR whether we were doing a release or not. This PR separates the jobs and just runs make on PRs and will run goreleaser anytime we tag a new release. This should unblock our PR backlog.
=> Separate build and release jobs

internal/blockchain/ethereum/besu/besu_provider.go, internal/blockchain/ethereum/besu/genesis.go, internal/blockchain/ethereum/connector/ethconnect/config.go, internal/blockchain/ethereum/connector/evmconnect/config.go, internal/blockchain/ethereum/ethsigner/config.go, internal/blockchain/ethereum/geth/genesis.go, internal/blockchain/tezos/connector/tezosconnect/config.go, internal/blockchain/tezos/tezossigner/config.go, internal/core/manifest_test.go, internal/docker/docker.go, internal/stacks/stack_manager.go
Fix small code issues, simplify code.
=> Fix small code issues, simplify code

go.mod, go.sum, internal/blockchain/ethereum/besu/besu_provider_test.go, internal/blockchain/ethereum/besu/genesis_test.go, internal/blockchain/ethereum/besu/testdata/genesis1_output.json, internal/blockchain/ethereum/besu/testdata/genesis2_output.json, internal/blockchain/ethereum/besu/testdata/test_contracts.json, internal/blockchain/ethereum/geth/genesis_test.go, internal/blockchain/ethereum/geth/geth_provider_test.go, internal/blockchain/ethereum/geth/testdata/genesis1_output.json, internal/blockchain/ethereum/geth/testdata/genesis2_output.json, internal/blockchain/ethereum/geth/testdata/test_contracts.json
This is pr fixes for #7 
@nguyer, @awrichar 
New Unit tests have been written for the ethereum blockchain node providers, the [Besu ](https://github.com/hyperledger/firefly-cli/blob/main/internal/blockchain/ethereum/besu/genesis.go)  and [geth](https://github.com/hyperledger/firefly-cli/tree/main/internal/blockchain/ethereum/geth) in the Ethereum Blockchain. 
These tests  pass successfully
=>  tests created for the  Ethereum  Blockchain node providers

cmd/accounts_create.go, cmd/accounts_list.go, cmd/deploy_ethereum.go, cmd/deploy_fabric.go, cmd/info.go, cmd/logs.go, cmd/prompt.go, cmd/pull.go, cmd/remove.go, cmd/reset.go, cmd/start.go, cmd/stop.go, cmd/upgrade.go
Resolves [273](https://github.com/hyperledger/firefly-cli/issues/273), added a function to the `ValidArgsFunction` field to add completion to command that requires stack name.
=> Included stack name completion.

internal/blockchain/ethereum/remoterpc/remoterpc_provider_test.go, internal/blockchain/fabric/fabconnect/client_test.go, internal/blockchain/fabric/fabconnect/fabconnect_config_test.go, internal/blockchain/fabric/fabconnect/testdata/fabconfig1.yaml, internal/blockchain/fabric/fabconnect/testdata/fabconfig2.yaml, internal/blockchain/fabric/fabconnect/testdata/fabconfig3.yaml, internal/blockchain/fabric/fabconnect/testdata/fabconfig4.yaml, internal/blockchain/fabric/fabric_provider_test.go, internal/blockchain/fabric/testdata/test_contracts.json
=> firefly-cli pkg and internal tests

cmd/init.go, internal/blockchain/ethereum/remoterpc/remoterpc_provider.go, internal/stacks/stack_manager.go, pkg/types/options.go, pkg/types/stack.go
Specifically, this option allows the `ff init` command to be run with `-n remote-rpc` without specifying `--contract-address`, something which was previously not supported.
By default the CLI will behave the same as previous versions. However, setting the new `--remote-node-deploy=true` option will perform both the deployment of the FireFly contract, and the identity/org registration. Effectively this option is a way of saying "the remote node is a free-gas chain", but I thought it might be possible to use for non-free-gas chains such as Polygon, if you had a way of ensuring your signing key had enough gas to pay for the deployment. Hence calling the new option `--remote-node-deploy`, not `--remote-node-free-gas` or similar.
=> Add an option '--remote-node-deploy' to treat remote nodes like local nodes

internal/blockchain/fabric/constants.go, internal/blockchain/fabric/fabric_provider.go
Related to: #https://github.com/hyperledger/firefly-cli/issues/268
I've run the E2E tests locally as @nguyer mentioned:
`DOWNLOAD_CLI=false STACK_TYPE=fabric TEST_SUITE=TestFabricMultipartyE2ESuite  MULTIPARTY_ENABLED=true  ./run.sh`
--- PASS: TestFabricMultipartyE2ESuite (137.02s)
--- PASS: TestFabricMultipartyE2ESuite/TestE2EBroadcast (3.97s)
--- PASS: TestFabricMultipartyE2ESuite/TestE2EBroadcastBlob (34.51s)
--- PASS: TestFabricMultipartyE2ESuite/TestE2EPrivate (3.74s)
--- PASS: TestFabricMultipartyE2ESuite/TestE2EPrivateBlobDatatypeTagged (3.71s)
--- PASS: TestFabricMultipartyE2ESuite/TestE2EWebhookExchange (7.61s)
--- PASS: TestFabricMultipartyE2ESuite/TestE2EWebhookRequestReplyNoTx (4.78s)
--- PASS: TestFabricMultipartyE2ESuite/TestStrongDatatypesBroadcast (7.58s)
--- PASS: …
=> feature: upgrade the Fabric version to v2.5 TLS

cmd/root.go, internal/core/manifest.go, internal/core/manifest_test.go, internal/stacks/stack_manager.go
The existing upgrade command is pretty limited in what it is able to do. It simply rewrites the stack.json and docker-compose file with newer image tags from a different version manifest. If there is any additional migration (such as config changes) required between versions it will not work.
As an example, when we moved all of the containers to run as a non-root user the FireFly CLI also had to be updated to put config files in a different location which a non-root user could read. This change was _backward_ compatible with older versions of FireFly, but older versions of the CLI would not be able to generate the proper config for _newer_ versions of FireFly. Thus, simply swapping the image tag would not work to move from 1.2.x -> 1.3.x because of permissions changes.
This PR sets some …
=> Limit upgrade command

.github/workflows/e2e.yml, internal/blockchain/fabric/constants.go, internal/blockchain/fabric/fabric_provider.go
I discovered that despite some of the job labels, all of the jobs in the matrix ended up testing the same type of stack. This PR brings the E2E matrix into alignment with the same set of tests we run in the FireFly Core repo.
=> Fix fabric-tools and update E2E matrix

internal/blockchain/ethereum/besu/genesis.go, internal/blockchain/ethereum/besu/genesis_test.go
The Besu genesis.json was getting created with an invalid extraData field which was causing it to fail to start up. This PR fixes that issue.
=> Fix Besu genesis

cmd/upgrade.go, internal/blockchain/fabric/fabric_provider.go, internal/stacks/prometheus_config.go, internal/stacks/stack_manager.go
This PR adds a `--force` flag to the upgrade command to allow upgrades between unsupported versions. This is useful to me in migration testing when I know how to "hack" around the reasons that the upgrade may have been unsupported.
This PR also fixes a few issues with deploying custom chaincode to Fabric networks.
Resolves https://github.com/hyperledger/firefly-cli/issues/297
=> Add `--force` flag to upgrade. Fix `deploy fabric` command.

internal/stacks/stack_manager.go
Fixes https://github.com/hyperledger/firefly-cli/issues/295
=> fix: no such volume error

cmd/init.go, internal/blockchain/ethereum/besu/besu_provider.go, internal/blockchain/ethereum/connector/ethconnect/docker.go, internal/blockchain/ethereum/connector/ethconnect/docker_test.go, internal/blockchain/ethereum/connector/evmconnect/docker.go, internal/blockchain/ethereum/connector/evmconnect/docker_test.go, internal/blockchain/ethereum/ethsigner/ethsigner.go, internal/blockchain/ethereum/geth/geth_provider.go, internal/blockchain/fabric/fabric_docker.go, internal/blockchain/fabric/fabric_provider.go, internal/blockchain/tezos/connector/tezosconnect/docker.go, internal/blockchain/tezos/tezossigner/tezossigner.go, internal/docker/docker_config.go, internal/docker/docker_config_test.go, internal/stacks/stack_manager.go, internal/tokens/erc1155/erc1155_provider.go, internal/tokens/erc20erc721/erc20_erc721_provider.go, pkg/types/options.go, pkg/types/stack.go
This PR adds a `--environment-vars` flag to the **init** command to allow docker compose generation to include generic environment variables across all containers. When docker is started against a corporate proxy, containers are unable to resolve via the internal DNS names due to the proxy. 
In this instance, users need to unset the proxy by passing in environment variables `HTTP_PROXY=,http_proxy=` to the containers. Depending on needs, other proxy specific environment variables can be set as well.
Resolves #302
=> Add environment vars cli flag to stack init

internal/core/manifest.go, internal/docker/docker_config.go, internal/stacks/stack_manager.go
Improve the health check of FireFly and logging if the manifest provided doesn't have a FF image
=> Add healthcheck for firefly and extra log info for image

cmd/init.go
After fix in this PR - quickly shows the simple environmental problem with my local setup:
```
initializing new FireFly stack...
Cleanup from previous error returned: stat /Users/pbroadhurst/.firefly/stacks/dev/docker-compose.yml: no such file or directory
Error: reading image "ghcr.io/hyperledger/firefly:latest": GET https://ghcr.io/token?scope=repository%3Ahyperledger%2Ffirefly%3Apull&service=ghcr.io: DENIED ....
```
Before fix in this PR - extremely confusing, as it doesn't mention the actual error:
```
ff init dev --block-period 1 -n quorum --private-transaction-manager tessera -c ethconnect 1 
initializing new FireFly stack...
Error: stat /Users/pbroadhurst/.firefly/stacks/dev/docker-compose.yml: no such file or directory
```
=> Cleanup code masking useful error message

.gitignore, internal/blockchain/ethereum/ethsigner/config.go, internal/blockchain/ethereum/quorum/quorum.go, internal/blockchain/ethereum/quorum/quorum_provider.go, internal/blockchain/ethereum/tessera/tessera.go, internal/blockchain/ethereum/tessera/tessera_test.go
I noticed after starting a Quroum developer environment with the CLI it was attempting to peer with the public list of ethereum nodes.
This PR adds the `--nodiscover` command line option to stop this.
Couple of other minor changes proposes:
- Moving `tessera` to its own directory
- code naming coupling directly to Quorum seemed a little confusing - as it does as a component work with HL Besu as well (even though that hasn't yet been contributed
- Changing the code checks to `Equals(types.PrivateTransactionManagerTessera)` for code blocks that are Tessera specific
- concept of `--private-transaction-manager` isn't exclusive to Tessera, and this will avoid catching out future contributions that provide other options
=> Add --nodiscover to Quorum command line

internal/blockchain/ethereum/quorum/quorum.go
Currently when starting multiple members Quorum network, there is an error being thrown when trying to register organization and nodes for members whom are not part of the bootnode (i.e. bootnodes are used for auto discovery of peers).
Removing --nodiscover flag from all members prevent nodes from being discovered by the bootnode. This PR is raised to retain the --nodiscover flag on the bootnode itself, while removing the flag on the remaining nodes so that they can be connected in the same network.
=> Remove --nodiscover from non bootnodes

internal/blockchain/ethereum/quorum/quorum.go
Tested with the following procedure locally:
```console
./ff init -b quorum q4
./ff start -v -b q4
```
verified that the startup sequence was successful, with the 3 FireFly instances bootstrapped and the orgs registered onchain successfully.
=> Fix on top of PR 320

.github/workflows/build.yml, Makefile, go.mod
Don't ask me how but Go 1.22.6 fixes the coverage broken pipe problem
See problem at https://github.com/hyperledger/firefly-cli/actions/runs/10832284030/job/30956922782#step:4:1
=> fix broken pipe code coverage

cmd/accounts_create.go, cmd/accounts_list_test.go, cmd/deploy_ethereum.go, cmd/deploy_fabric.go, cmd/ps.go, cmd/root.go, cmd/version.go, internal/blockchain/fabric/fabric_provider.go
This PR enhances the FireFly CLI by making the executable name dynamic in the help messages. Instead of hardcoding the executable name, it is now loaded from the command-line arguments, allowing for dynamic help messages that reflect the actual executable name being used.
Before:
```
% firefly
To get started run: ff init
Optional: Set FIREFLY_HOME env variable for FireFly stack configuration path.
Usage:
ff [command]
```
After:
```
% firefly
To get started run: firefly init
Optional: Set FIREFLY_HOME env variable for FireFly stack configuration path.
Usage:
firefly [command]
```
=> chore: Get executable name from the command

.golangci.yml, cmd/init_fabric.go
Inspired by https://github.com/hyperledger/firefly/pull/1649/files
Fixes: https://github.com/hyperledger/firefly-cli/actions/runs/12630600319/job/35190729382 that complains about a year change when the file hasn't been changed
=> Relax year check on copyright header in golangci lint

.goreleaser.yml
Failure in v1.3.3 release https://github.com/hyperledger/firefly-cli/actions/runs/14037243248/job/39298579545 is caused by the `GoReleaser` tool thinking the release candidate `v1.3.3-rc.1` is the newest one because of the way it sorts..
Found https://github.com/goreleaser/goreleaser/pull/3611/files#diff-387a86836bbc80da7865b5ccf079e7b6d7c82a673d5c6538892e24e1bdf17d14R9-R14
=> Sort Git tag by date in goreleaser
