hyperledger/firefly-cli

cmd/logs.go
cmd/remove.go
cmd/reset.go
cmd/root.go
internal/stacks/dockerConfig.go
internal/stacks/stack.go

- Move data inside containers (don't mount volumes in the data directory anymore)
- Update `reset` command to wipe containers (keeping config only)
- Fix bugs with `reset` command
- Add `-f` flag to `reset` command to force the operation

Postgres improvements

---

README.md
cmd/init.go
cmd/logs.go
cmd/remove.go
cmd/reset.go
cmd/start.go
cmd/stop.go
ff/main.go
go.mod
internal/contracts/contracts.go
internal/stacks/stack.go

Rename package and ethconnect headers

---

internal/stacks/dockerConfig.go

To make sure you always have the latest images you can run these commands:
```
docker pull ghcr.io/hyperledger-labs/firefly:latest
docker pull ghcr.io/hyperledger-labs/firefly-ethconnect:latest
docker pull ghcr.io/hyperledger-labs/firefly-dataexchange-https:latest
```

Update docker image paths to hyperledger repos

---

internal/stacks/dockerConfig.go
internal/stacks/ganache/Dockerfile
internal/stacks/ganache/healthcheck.sh
internal/stacks/stack.go

This should ensure the correct startup order for dependencies, should fix https://github.com/hyperledger-labs/firefly-cli/issues/35

Add healthcheck for ganache

---

internal/stacks/fireflyIdentity.go

Signed-off-by: Andrew Richardson <andrew.richardson@kaleido.io>

Use 127.0.0.1 instead of localhost

---

internal/stacks/stack.go

This should resolve https://github.com/hyperledger-labs/firefly-cli/issues/52

Check port availability before starting stack

---

cmd/init.go
cmd/list.go
cmd/prompt.go
cmd/remove.go
cmd/reset.go
cmd/root.go
go.mod
go.sum

* Remove promptui
* Fix compatability with Git Bash
Resolves https://github.com/hyperledger-labs/firefly-cli/issues/53
Resolves https://github.com/hyperledger-labs/firefly-cli/issues/54

Improve init validation and interactive prompts

---

internal/stacks/stack.go

Do not remove images on ff reset/remove

---

internal/geth/client.go
internal/stacks/stack.go

This should fix timing issues running the CLI in GitHub actions or other slower environments

Ensure ethereum accounts unlocked before proceeding

---

internal/stacks/fireflyIdentity.go
internal/stacks/stack.go

These are the commits originally in #79 but not specifically related to tokens.

Minor enhancements to contract/REST calls

---

cmd/init.go
internal/blockchain/blockchain_provider.go
internal/blockchain/ethereum/besu/besu_provider.go
internal/blockchain/ethereum/contracts.go
internal/blockchain/ethereum/geth/geth_provider.go
internal/core/firefly_config.go
internal/core/http.go
internal/stacks/firefly_identity.go
internal/stacks/stack_manager.go
internal/stacks/types.go
internal/tokens/erc1155/contracts.go
internal/tokens/erc1155/erc1155_provider.go
internal/tokens/niltokens/niltokens_provider.go
internal/tokens/tokens_provider.go
pkg/types/stack.go

Tokens Docker will need to be deployed before this can work, which implies a dependency on https://github.com/hyperledger-labs/firefly-tokens-erc1155/pull/3. **Edit:** this pre-req is now [done](https://github.com/hyperledger-labs/firefly-tokens-erc1155/pkgs/container/firefly-tokens-erc1155).

Deploy ERC1155 contract and tokens microservice

---

CONTRIBUTING.md
README.md
cmd/info.go
cmd/init.go
cmd/list.go
cmd/logs.go
cmd/ls.go
cmd/remove.go
cmd/reset.go
cmd/root.go
cmd/start.go
cmd/stop.go
cmd/upgrade.go
ff/main.go
go.mod
internal/blockchain/blockchain_provider.go
internal/blockchain/ethereum/besu/besu_provider.go
internal/blockchain/ethereum/contracts.go
internal/blockchain/ethereum/ethconnect/client.go
internal/blockchain/ethereum/ethconnect/docker.go
internal/blockchain/ethereum/geth/geth_provider.go
internal/core/firefly_config.go
internal/docker/docker_config.go
internal/stacks/firefly_identity.go
internal/stacks/stack_manager.go
internal/tokens/erc1155/contracts.go
internal/tokens/erc1155/erc1155_provider.go
internal/tokens/niltokens/niltokens_provider.go
internal/tokens/tokens_provider.go

I have tested this locally and it creates and runs a working stack from the latest images that are now published under Hyperledger

Hyperledger move

---

internal/core/firefly_config.go
internal/tokens/erc1155/erc1155_provider.go

Depends on https://github.com/hyperledger/firefly/pull/202

Update token config keys

---

internal/core/firefly_config.go
internal/stacks/stack_manager.go

Fix mismatched member configs

---

Makefile

Signed-off-by: Apoorva Mahabaleshwara <apoorvambhat@gmail.com>

Adding linter in Makefile to catch lint issues

---

Makefile

Signed-off-by: Apoorva Mahabaleshwara <apoorvambhat@gmail.com>

Adding help section to Makefile

---

internal/blockchain/ethereum/besu/besu_provider.go
internal/blockchain/ethereum/ethconnect/config.go
internal/blockchain/ethereum/ethconnect/docker.go
internal/blockchain/ethereum/geth/geth_provider.go

This PR adds an external config file for ethconnect (both for geth and besu) and sets a few parameters to reduce transaction latency.

Use external config for ethconnect

---

cmd/logs.go

Resolves https://github.com/hyperledger/firefly-cli/issues/96

Fix logs comand

---

go.mod
go.sum

Signed-off-by: Peter Broadhurst <peter.broadhurst@kaleido.io>

Update protobuf dep

---

internal/blockchain/ethereum/geth/geth_provider.go

@nguyer Suggested I might make a project contribution to allow remix to be better supported. Looking forward to feedback.

Add corsdomain clause to support local development

---

internal/core/firefly_config.go

This was officially renamed back in https://github.com/hyperledger/firefly/pull/538
Fixes #191

Replace "publicstorage" key with "sharedstorage"

---

internal/docker/docker_config.go
internal/stacks/ipfs_config.go
internal/stacks/stack_manager.go

This allows the file to be easily modified outside of the container.

Use host mount instead of volume for firefly.core.yml

---

.goreleaser.yml

Make goreleaser honor pre-release tags

---

internal/blockchain/ethereum/ethsigner/ethsigner.go
internal/stacks/stack_manager.go
pkg/types/manifest.go

Add firefly-signer to manifest

---

internal/blockchain/ethereum/besu/besu_provider.go
internal/blockchain/ethereum/ethsigner/config.go
internal/blockchain/ethereum/geth/geth_provider.go
internal/blockchain/ethereum/remoterpc/remoterpc_provider.go
internal/blockchain/fabric/fabric_provider.go

Resolves https://github.com/hyperledger/firefly-cli/issues/208

Fix blockchain connector URL with -e flag

---

internal/core/config.go
internal/docker/docker_config.go
internal/stacks/stack_manager.go

See https://github.com/hyperledger/firefly/pull/1037 and https://github.com/hyperledger/firefly/pull/1034

Enable all plugins for gateway mode, allowing data+IPFS for NFT data etc.

---

internal/stacks/stack_manager.go

Resolves https://github.com/hyperledger/firefly-cli/issues/218

Fix startup flow for existing contract

---

CONTRIBUTING.md

Most of the firefly-* repos seem to have the same issue so I might tidy those up as well shortly.
Signed-off-by: Matthew Whitehead <matthew.whitehead@kaleido.io>

Update the link to the contributor guidelines html

---

cmd/init.go

Add support for setting custom org and node names non-interactively

---

cmd/init.go
cmd/init_ethereum.go
internal/core/manifest.go

Resolves https://github.com/hyperledger/firefly/issues/1135
Resolves https://github.com/hyperledger/firefly-cli/issues/233

Set default connector to evmconnect

---

cmd/init.go
internal/core/manifest.go
internal/core/manifest_test.go
internal/stacks/stack_manager.go
pkg/types/options.go

Also resolves https://github.com/hyperledger/firefly-cli/issues/160

Fix version manifest fetching

---

cmd/pull.go
cmd/start.go
internal/log/spin.go

Fix the spinner logger

---

internal/core/config.go
internal/stacks/stack_manager.go
pkg/types/firefly_config.go
pkg/types/namespace.go

Remove deprecated global node config

---

go.mod
go.sum
internal/blockchain/fabric/fabconnect/client_test.go
internal/utils/testing.go

This is pr fixes for #7 
@nguyer, @awrichar
This Pr contains environment setups, when writing unit tests for the firefly-cli codebase, and It also contains test for the [fabric](https://github.com/hyperledger/firefly-cli/tree/main/internal/blockchain/fabric) blockchain package .

test environment setups

---

cmd/ps.go
internal/docker/docker.go
internal/stacks/stack_manager.go

Resolves [#221](https://github.com/hyperledger/firefly-cli/issues/221), to specify stacks that are running.

Resolves #221, show currently running stacks.

---

.gitignore
cmd/docs.go
go.sum

This commit is a new feature (introduces a new command - `docs`) that generates a markdown documentation of all command.

New feature (docs command)

---

cmd/start.go

Resolve #192, added Swagger API UI url to stdout for `start` command.

Resolve #192, added Swagger API UI url to stdout for `start` command.

---

internal/blockchain/ethereum/besu/besu_provider.go
internal/blockchain/ethereum/connector/connector_interface.go
internal/blockchain/ethereum/connector/ethconnect/client.go
internal/blockchain/ethereum/connector/evmconnect/client.go
internal/blockchain/ethereum/connector/evmconnect/docker.go
internal/blockchain/ethereum/geth/geth_provider.go
internal/blockchain/ethereum/remoterpc/remoterpc_provider.go
internal/stacks/stack_manager.go

After updating the EVMConnect and DX images in the FireFly manifest, I ran into file permission issues again. This PR fixes that.

More fixes for directory permissions

---

internal/stacks/prometheus_config.go

Fixing https://github.com/hyperledger/firefly-cli/actions/runs/8391240576/job/22981125133

Add missing copyright header to fix build

---

.github/workflows/e2e.yml
internal/docker/docker_checks.go

V1 is actually end of life https://github.com/docker/compose/issues/11742#issuecomment-2137583574 so prioritise docker compose v2

Prioritise docker compose v2

---

cmd/init_fabric.go

This pull request resolves the issue referenced at https://github.com/hyperledger/firefly/issues/1533

set CtxComposeVersionKey in initFabricCmd
